name: Java CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build-and-push:
    name: ðŸ“¦ Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # needed so GitHub Actions can authenticate to GHCR
      id-token: write

    steps:
      - name: Checkout
        if: github.repository == 'PCSX2/hifumi'
        uses: actions/checkout@v6

      - name: Log in to GHCR
        if: github.repository == 'PCSX2/hifumi'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        if: github.repository == 'PCSX2/hifumi'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # FIXME: replace these when transitioning repo ownership
          tags: |
            ghcr.io/pcsx2/hifumi:latest
            ghcr.io/pcsx2/hifumi:${{ github.ref_name }}
